import DionPosterImg from "../asset/img/club_poster/DION-Poster.svg";
import CatPosterImg from "../asset/img/club_poster/Cat-Poster.svg";
import AssisiPosterImg from "../asset/img/club_poster/ASSISI-Poster.svg";
import PalermoPosterImg from "../asset/img/club_poster/PALERMO-poster.svg";
import PineappleImg from "../asset/img/club_poster/Pineapple-Poster.svg";

export const clublist = [
  {
    posterImg: DionPosterImg,
    clubCategory: "창체",
    clubName: "DION",
    clubIntroduction: "새로운 멤버를 모집합니다.",
    recruitmentStatus: "모집중",
    recruitnumber: "6",
    recruitField: "웹프론트 2명, 안드 2명, 서버 2명",
    supportTarget: "1학년, 2학년 재학생",
    recruitPeriod: "2024. 03. 04(월) ~ 2024. 03. 10(일)",
    interviewSchedule: "추후 공지",
    applyLink: "https://forms.gle/h6Uq62RhncwRYDX88",
  },
  {
    posterImg: CatPosterImg,
    clubCategory: "자율",
    clubName: "Cat",
    clubIntroduction: "고양이가 세상을 지배한다.",
    recruitmentStatus: "모집중",
    recruitnumber: "2",
    recruitField: "무관",
    supportTarget: "1학년 재학생",
    recruitPeriod: "2024. 03. 04(월) ~ 2024. 03. 10(일)",
    interviewSchedule: "추후 공지",
    applyLink: "https://docs.google.com/forms/u/0/?tgif=d",
  },
  {
    posterImg: AssisiPosterImg,
    clubCategory: "창체",
    clubName: "Assisi",
    clubIntroduction: "뭐하는 동아리일까?",
    recruitmentStatus: "모집중",
    recruitnumber: "4",
    recruitField: "안드 2명, iOS 2명",
    supportTarget: "1학년 재학생",
    recruitPeriod: "2024. 03. 04(월) ~ 2024. 03. 10(일)",
    interviewSchedule: "추후 공지",
    applyLink: "https://docs.google.com/forms/u/0/?tgif=d",
  },
  {
    posterImg: PalermoPosterImg,
    clubCategory: "창체",
    clubName: "Palermo",
    clubIntroduction: "뭐하는 동아리일가??222",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: PineappleImg,
    clubCategory: "자율",
    clubName: "Pineapple",
    clubIntroduction: "파인애플, 그것은 무엇인가",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: DionPosterImg,
    clubCategory: "창체",
    clubName: "DION",
    clubIntroduction: "새로운 멤버를 모집합니다.",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: CatPosterImg,
    clubCategory: "자율",
    clubName: "Cat",
    clubIntroduction: "고양이가 세상을 지배한다.",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: AssisiPosterImg,
    clubCategory: "창체",
    clubName: "Assisi",
    clubIntroduction: "뭐하는 동아리일까?",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: PalermoPosterImg,
    clubCategory: "창체",
    clubName: "Palermo",
    clubIntroduction: "뭐하는 동아리일가??222",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: PineappleImg,
    clubCategory: "자율",
    clubName: "Pineapple",
    clubIntroduction: "파인애플, 그것은 무엇인가",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: DionPosterImg,
    clubCategory: "창체",
    clubName: "DION",
    clubIntroduction: "새로운 멤버를 모집합니다.",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: CatPosterImg,
    clubCategory: "자율",
    clubName: "Cat",
    clubIntroduction: "고양이가 세상을 지배한다.",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: AssisiPosterImg,
    clubCategory: "창체",
    clubName: "Assisi",
    clubIntroduction: "뭐하는 동아리일까?",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: PalermoPosterImg,
    clubCategory: "창체",
    clubName: "Palermo",
    clubIntroduction: "뭐하는 동아리일가??222",
    recruitmentStatus: "모집중",
  },
  {
    posterImg: PineappleImg,
    clubCategory: "자율",
    clubName: "Pineapple",
    clubIntroduction: "파인애플, 그것은 무엇인가",
    recruitmentStatus: "모집중",
  },
];
