export const noticelist = [
  {
    clubName: "dion",
    id: 1,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김언수",
  },
  {
    clubName: "dion",
    id: 2,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김빙수",
  },
  {
    clubName: "dion",
    id: 3,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김언수",
  },
  {
    clubName: "dion",
    id: 4,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김빙수",
  },
  {
    clubName: "dion",
    id: 5,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김언수",
  },
  {
    clubName: "dion",
    id: 6,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김빙수",
  },
  {
    clubName: "dion",
    id: 7,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김언수",
  },
  {
    clubName: "dion",
    id: 8,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김빙수",
  },
  {
    clubName: "dion",
    id: 9,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김언수",
  },
  {
    clubName: "dion",
    id: 10,
    title: "동아리 홍보 PPT 공유합니다",
    writingDate: "2024.04.19",
    user: "김빙수",
  },
];
